version: '3.8'

services:
  mysqldb:
    image: mysql
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQLDB_PASSWORD
      - MYSQL_DATABASE=$MYSQLDB_DATABASE
    ports:
        - $MYSQLDB_PORT:$MYSQLDB_DOCKER_PORT
  redisdb: 
    image: redis
    ports:
     - "$REDIS_PORT:$REDIS_DOCKER_PORT"
    expose:
      - 6379
  app:
    depends_on:
      - mysqldb
      - redisdb
    build: ./
    restart: unless-stopped
    env_file: ./.env
    ports:
      - $NODE_PORT:$NODE_DOCKER_PORT
      - $SOCKET_PORT:$SOCKET_DOCKER_PORT
    environment:
      - MYSQLDB_HOST=mysqldb
      - MYSQLDB_USERNAME=$MYSQLDB_USERNAME
      - MYSQLDB_PASSWORD=$MYSQLDB_PASSWORD
      - MYSQLDB_DATABASE=$MYSQLDB_DATABASE
      - SOCKET_PORT=$SOCKET_PORT
      - SOCKET_ORIGIN=$SOCKET_ORIGIN
      - REDIS_HOST=redisdb
      - REDIS_PORT=$REDIS_PORT